apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-hello-container
        image: sukhkar/python_docker_container:latest
        ports:
        - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: python-app-dev
spec:
  selector:
    app: python-app
  ports:
  - port: 8085
    targetPort: 8085
  type: LoadBalancer
